### ISSUE TITLE
Missing Lat,Lng Info for Zip Codes

### ISSUE THREAD

**Issue by berch** [MacHu-GWU/uszipcode-project#5]
Some zip codes that are in free-zipcode-database-Primary.csv, but their lat, lng info cannot be called. 

For example:

from uszipcode import ZipcodeSearchEngine
search = ZipcodeSearchEngine()
o = search.by_zipcode(30724)
o.Latitude

This call returns nothing, but it is clearly a zip code for Eton Georgia that is in the csv.

**Comment by MacHu-GWU** [comment]
Because the data base I am using here is a intersect of free-zipcode-database-Primary.csv and zcta2010.csv and it's latest google geocoding result. 30724 is not included in uszipcode database. If you search it on google, it's just a very small piece of area. 

If you are looking for geo data but not census data, I recommend [Geomate](https://pypi.python.org/pypi/geomate), another project can easily do batch geocoding.

Thank you

**Comment by berch** [comment]
I am using your package to do zip code to lat-lng conversion. I was just surprised that some well used zip codes are not included. 30724 is not the only one. I have other examples as well. Have you considered including zipcodes with incomplete information? I am assuming that's why it is not in the uszipcode db.

**Comment by MacHu-GWU** [comment]
Hum, I will take that into next patch, will include as many information as I can. For those information doesn't have census data, I will also include them into next version.

The advantage of this is because the geo info is the latest. There's a lot of error in free-zipcode-database-Primary.csv and zcta2010.csv  dataset. I am using the latest google data.
