### ISSUE TITLE
What are the  different sources of data being used in this package and how old are those datasets?

### ISSUE THREAD

**Issue by jwaladhamala** [MacHu-GWU/uszipcode-project#52]
What is the source of this dataset?

Stats and Demographics

population
population_density
population_by_year
population_by_age
population_by_gender
population_by_race
head_of_household_by_age
families_vs_singles
households_with_kids
children_by_age

**Comment by nouyang** [comment]
Looking at the source code and commits since 2016.
The database is updated 2019.
https://datahub.io/machu-gwu/uszipcode-0.2.0-simple_db

WE can't say for certain what is in the database. There are a few about.rst files which give clues.

https://github.com/MacHu-GWU/uszipcode-project/tree/master/dataset
https://github.com/MacHu-GWU/uszipcode-project/blob/master/dataset/federalgovernmentzipcodes/about.rst
https://github.com/MacHu-GWU/uszipcode-project/blob/master/dataset/zcta2010/about.rst

**2010 census data** 
According to the about file it is pulled from 
> http://proximityone.com/cen2010_zcta_dp.htm, 

which has more details here

> http://proximityone.com/rankingtables.htm#puma

There you can clikc and see.

> These data are based on the American Community Survey (ACS) 2012 1-year estimates. 
> http://proximityone.com/puma12dp1.htm

>Census 2010 and ACS 2012 provide the most current Census-sourced demographics for wide-ranging geography.  http://proximityone.com/puma12dp1.htm

> Public Use Microdata Areas (PUMAs) --  https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas.html

**Comment by MacHu-GWU** [comment]
To be honest, I don't know the correctness of the Stats and Demographics. This data source is mostly from open census data.
